require ('options')
require ('plugins')
require ('bufferline-config')
require ('lualine-config')
require ('cmp-config')
require ('lsp-config')
require ('treesitter-config')
require ('telescope-config')
require ('alpha-config')
require ('autopairs-config')
require ('impatient-config')
require ('nvim-tree-config')

vim.cmd("colorscheme nightfox")
